{
  parserClass="com.github.alonalbert.ijgrammar.grammar.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.alonalbert.ijgrammar.grammar"
  psiImplPackage="com.github.alonalbert.ijgrammar.grammar.impl"

  elementTypeHolderClass="com.github.alonalbert.ijgrammar.grammar.SimpleTypes"
  elementTypeClass="com.github.alonalbert.ijgrammar.grammar.SimpleElementType"
  tokenTypeClass="com.github.alonalbert.ijgrammar.grammar.SimpleTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY
